version: "3.9"
services:
  # api:
  #   build:
  #     context: ./server
  #     dockerfile: Dockerfile
  #   container_name: api
  #   restart: always
  #   ports:
  #     - 8000:8000
  #   volumes:
  #     - "./server:/usr/src/app"
  # depends_on:
  # - rabbitmq

  # worker:
  #   build:
  #     context: ./server
  #     dockerfile: ./server/worker.Dockerfile
  #   restart: on-failure
  #   container_name: worker
  #   volumes:
  #     - .:/server
  #   command: bash -c "celery -A application.tasks worker --loglevel=INFO"
  #   #depends_on:
  #   # - rabbitmq

  rabbitmq:
    image: "rabbitmq:3.9.5-management-alpine"
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - network
networks:
  network: {}
