version: "3.9"
services:
  # web:
  #   build:
  #     context: ./server
  #     dockerfile: ./docker/web
  #   container_name: web
  #   ports:
  #     - "8888:8888"
  #   volumes:
  #     - .:/server
  #   depends_on:
  #     - rabbitmq

  # worker:
  #   build:
  #     context: ./server
  #     dockerfile: ./docker/worker
  #   container_name: worker
  #   volumes:
  #     - .:/server
  #   depends_on:
  #     - rabbitmq
  #     - web

  rabbitmq:
    image: "rabbitmq:3.9.5-management-alpine"
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - network

networks:
  network: {}
