ROOT = "http://localhost:8888/"
API_PREFIX = '/api'
UPLOAD_FOLDER = "storage/"
TMP_FOLDER = "/var/tmp/"
TMP_SUFFIX = "_tmp"
SEP_UID_NAME = "_S_"
API_AUTH = "112233"
IMG_FOLDER = 'assets/imgs'
POPPLER_PATH='/usr/local/bin'
